#pragma config(Hubs,   S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S4,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     ElevStage1,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     ElevStage2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     TreadLeft,     tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C2_2,     TreadRight,    tmotorTetrix, openLoop, driveRight)
#pragma config(Servo,  srvo_S1_C3_1,    ScoopGate,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    TrailerHookLeft,      tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    TrailerHookRight,     tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "constants.h"
#include "macros.h"
#include "config.h"

#include "JoystickDriver.c"

/*
 * Initialize Robot
 */
void initialize() {
	// Close Scoop Gate
  servo[ScoopGate]        = SCOOPGATE_CLOSED;

  // Raise Trailer Hooks
  servo[TrailerHookLeft]  = TRAILERHOOKLEFT_UP;
  servo[TrailerHookRight] = TRAILERHOOKRIGHT_UP;
}

/*
 * Drive State Machine
 *
 * Timer: T1
 */
void driveMachine() {
  static int state = 0;

  switch (state) {
 		case 0:
  		clearTimer(T1);
  	  motor[TreadLeft]  = AUTO_TREAD_SPEED;
      motor[TreadRight] = AUTO_TREAD_SPEED;

      state++;
      break;
    case 1:
      if (time1[T1] > AUTO_TREAD_TIME) {
  	 		motor[TreadLeft]  = OFF;
  			motor[TreadRight] = OFF;

  			state++;
  		}
 			break;
  }
}

/*
 * Lift State Machine
 *
 * Timer: T2
 */
void liftMachine() {
  static int state = 0;

  switch (state) {
  	case 0:
			motor[ElevStage1] = ELEVSTAGE1_SPEED;
			clearTimer(T2);

			state++;
   	  break;
    case 1:
      if (time1[T2] > AUTO_ELEVSTAGE1) {
      	motor[ElevStage1] = OFF;

   	    state++;
   	  }
   	  break;
   	case 2:
			motor[ElevStage2] = ELEVSTAGE2_SPEED;
			clearTimer(T2);

			state++;
   	  break;
    case 3:
      if (time1[T2] > AUTO_ELEVSTAGE2) {
      	motor[ElevStage] = OFF;

   	    state++;
   	  }
   	  break;
  }
}

/* State Machine Scheduler */
task main(){
  initialize();
  startTask(displayDiagnostics);
  waitForStart();

  while (true) {
    liftMachine();
    driveMachine();
  }
/*
  // Wave servo
  servo[ScoopGate]  = SCOOPGATE_OPEN;
  delay(AUTO_SERVO);
  servo[ScoopGate]  = SCOOPGATE_CLOSED;
  delay(AUTO_SERVO);

  // Open scoop
  servo[ScoopGate]  = SCOOPGATE_OPEN;
  delay(AUTO_SERVO);
  // Lurch forward
  motor[TreadRight] = LURCH_SPEED;
  motor[TreadLeft]  = LURCH_SPEED;
  delay(LURCH_TIME);
  motor[TreadRight] = OFF;
  motor[TreadLeft]  = OFF;
  delay(AUTO_SERVO);
  // Close scoop
  servo[ScoopGate]  = SCOOPGATE_CLOSED;
 */
}
