#ifndef CONFIG_H
#define CONFIG_H

#define AUTO_TREAD_SPEED 50
#define AUTO_TREAD_TIME 4200
#define AUTO_ELEVSTAGE1_INIT 1000
#define AUTO_ELEVSTAGE1_SCORE 2250
#define AUTO_ELEVSTAGE2_SCORE 2500
#define AUTO_SERVO 1500

#define TURN_SPEED 100
#define TURN_TIME  700

#define LURCH_SPEED 50
#define LURCH_TIME  100

#define ELEVSTAGE1_SPEED 25
#define ELEVSTAGE2_SPEED 90

#define SCOOPGATE_OPEN 120
#define SCOOPGATE_CLOSED 245

#define TRAILERHOOKLEFT_UP 0
#define TRAILERHOOKRIGHT_UP 255
#define TRAILERHOOKLEFT_DOWN 230
#define TRAILERHOOKRIGHT_DOWN 25

#define TREAD_DEADZONE 25
#define TREAD_SENSITIVITY_PRECISE 4
#define TREAD_SENSITIVITY_NORMAL 2
#define TREAD_SENSITIVITY_TURBO 1

#endif // CONFIG_H
