#pragma config(Hubs,   S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S4,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     ElevStage1,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     ElevStage2,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     TreadLeft,     tmotorTetrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C2_2,     TreadRight,    tmotorTetrix, openLoop, driveRight)
#pragma config(Servo,  srvo_S1_C3_1,    ScoopGate,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    TrailerHookLeft,      tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    TrailerHookRight,     tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "constants.h"
#include "macros.h"
#include "config.h"
#include "JoystickDriver.c"

/*
 * Initialize Robot
 */
void setup() {
  servo[ScoopGate]        = SCOOPGATE_CLOSED;
  servo[TrailerHookLeft]  = TRAILERHOOKLEFT_UP;
  servo[TrailerHookRight] = TRAILERHOOKRIGHT_UP;
}

/*
 * Control Loop
 */
task main(){
  volatile bool disabled         = false;
  volatile bool lurched          = false;
  volatile int tread_sensitivity = 0;

  // Initialize
  setup();
  // FIRST FCS
  startTask(displayDiagnostics);
  waitForStart();

  while (true) {
  	// Read joystick controls
    getJoystickSettings(joystick);

    /*
     * Safety (1/2)
     *
     * Back: Toggle Safety
     */
    if (J1BUTTON(BTN_BACK) || J2BUTTON(BTN_BACK)) {
      if disabled
        disabled = false;
    	else
        disabled = true;
    } else if (disabled)
    	continue;
    }

    /*
     * Turbo/Precision (1)
     *
     * Left Bumper: Turbo
     * Right Bumper: Precision
     */
    if (J1BUTTON(BTN_LB)) {
      tread_sensitivity = TREAD_SENSITIVITY_TURBO;
    } else if (J1BUTTON(BTN_RB)) {
      tread_sensitivity = TREAD_SENSITIVITY_PRECISE;
    } else {
      tread_sensitivity = TREAD_SENSITIVITY_NORMAL;
    }

    /*
     * Tread Drive (1)
     *
     * Left Joystick: Left Tread
     * Right Joystick: Right Tread
     */
    if (abs(joystick.joy1_y1) > TREAD_DEADZONE) {
      motor[TreadLeft] = joystick.joy1_y1 / tread_sensitivity;
    } else {
      motor[TreadLeft] = OFF;
    }
    if (abs(joystick.joy1_y2) > TREAD_DEADZONE) {
      motor[TreadRight] = joystick.joy1_y2 / tread_sensitivity;
    } else {
      motor[TreadRight] = OFF;
    }

    /*
     * 90 Degree Turn (1)
     *
     * Left Trigger: Counterclockwise
     * Right Trigger: Clockwise
     */
    if (J1BUTTON(BTN_LT)) {
      motor[TreadLeft]  = -TURN_SPEED;
      motor[TreadRight] = TURN_SPEED;
      delay(TURN_TIME);
      motor[TreadLeft]  = OFF;
      motor[TreadRight] = OFF;
    } else if (J1BUTTON(BTN_RT)) {
      motor[TreadLeft]  = TURN_SPEED;
      motor[TreadRight] = -TURN_SPEED;
      delay(TURN_TIME);
      motor[TreadLeft]  = OFF;
      motor[TreadRight] = OFF;
    }

    /*
     * Lurch (1/2)
     *
     * B: Forward
     * A: Backward
     */
    if (J1BUTTON(BTN_B) || J2BUTTON(BTN_B)) {
      if (!lurched) {
        motor[TreadLeft]  = LURCH_SPEED;
        motor[TreadRight] = LURCH_SPEED;
        delay(LURCH_TIME);
        motor[TreadLeft]  = OFF;
        motor[TreadRight] = OFF;
        lurched = true;
      } else {
        lurched = false;
      }
    } else if (J1BUTTON(BTN_A) || J2BUTTON(BTN_A)) {
      if (!lurched) {
        motor[TreadLeft]  = -LURCH_SPEED;
        motor[TreadRight] = -LURCH_SPEED;
        delay(LURCH_TIME);
        motor[TreadLeft]  = OFF;
        motor[TreadRight] = OFF;
        lurched = true;
      } else {
        lurched = false;
      }
    }

    /*
     * Elevator (2)
     *
     * Left Bumper: Stage 1 Up
     * Left Trigger: Stage 1 Down
     * Right Bumper: Stage 2 Up
     * Right Trigger: Stage 2 Down
     */
    if (J2BUTTON(BTN_LB)) {
      motor[ElevStage1] = ELEVSTAGE1_SPEED;
    } else if (J2BUTTON(BTN_LT)) {
      motor[ElevStage1] = -ELEVSTAGE1_SPEED;
    } else if (J2BUTTON(BTN_RB)) {
      motor[ElevStage2] = ELEVSTAGE2_SPEED;
    } else if (J2BUTTON(BTN_RT)) {
      motor[ElevStage2] = -ELEVSTAGE2_SPEED;
    } else {
      motor[ElevStage1] = OFF;
      motor[ElevStage2] = OFF;
    }

    /*
     * Servos (2)
     *
     * Tophat Up: Scoop Gate Open
     * Tophat Down: Scoop Gate Closed
     * Tophat Left: Trailer Hook Up
     * Tophat Right: Trailer Hook Down
     */
    if (J2TOPHAT(TH_U)) {
      servo[ScoopGate]        = SCOOPGATE_OPEN;
    } else if (J2TOPHAT(TH_B)) {
      servo[ScoopGate]        = SCOOPGATE_CLOSED;
    } else if (J2TOPHAT(TH_L)) {
      servo[TrailerHookLeft]  = TRAILERHOOKLEFT_UP;
      servo[TrailerHookRight] = TRAILERHOOKRIGHT_UP;
    } else if (J2TOPHAT(TH_R)) {
      servo[TrailerHookLeft]  = TRAILERHOOKLEFT_DOWN;
      servo[TrailerHookRight] = TRAILERHOOKRIGHT_DOWN;
    }
  }
}
